obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_BQ2597X_MMI_CHARGER)	+= bq2597x_mmi/
obj-$(CONFIG_MMI_PARALLEL_CHARGER)	+= mmi_parallel_charger/
